name: Test nimo3

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
          
    - name: Install dependencies
      run: bun install
      
    - name: Run type check
      run: bun run type-check || npx tsc --noEmit
      
    - name: Run linting
      run: bun run lint || npx eslint src --ext .ts,.tsx
      
    - name: Build project
      run: bun run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_ELEVENLABS_API_KEY: ${{ secrets.VITE_ELEVENLABS_API_KEY }}
        
    - name: Test build output
      run: |
        if [ -d "dist" ]; then
          echo "✅ Build successful - dist directory exists"
          ls -la dist/
        else
          echo "❌ Build failed - dist directory not found"
          exit 1
        fi 